language: ruby

rvm:
  - 2.5.0

script:
  - bundle exec rails test

env:
  global:
    - ADMIN_NAME=admin
    - ADMIN_PASSWORD=admin
    - MEETUP_API_KEY=test
    - DATABASE_URL="postgres://postgres:localhost/rhyme_test?sslmode=disalbe"
