language: ruby

rvm:
  - 2.5.0

script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rails test

env:
  global:
    - ADMIN_NAME=admin
    - ADMIN_PASSWORD=admin
    - MEETUP_API_KEY=test
    - DATABASE_URL="postgres://postgres@localhost/banitsa_test"
