default: &default
  adapter: litedb
  encoding: unicode

development:
  <<: *default
  database: <%= Litesupport.root("development").join("data.sqlite3") %>

test:
  <<: *default
  database: <%= Litesupport.root("test").join("data.sqlite3") %>

production:
  <<: *default
  database: <%= Litesupport.root("production").join("data.sqlite3") %>
