default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development/data.sqlite3

test:
  <<: *default
  database: db/test/data.sqlite3

# The db/production directory is mounted as a persistent Docker volume by hamal.
production:
  primary:
    <<: *default
    database: db/production/data.sqlite3
  cache:
    <<: *default
    database: db/production/cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: db/production/queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: db/production/cable.sqlite3
    migrations_paths: db/cable_migrate
